import { Product } from "../models/Product";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const API_URL = "https://fakestoreapi.com";

export const productApi = createApi({
    reducerPath: 'productApi', // A unique name for the API slice
    baseQuery: fetchBaseQuery({ baseUrl: API_URL }), // The base URL for the API
    endpoints: (builder) => ({
        getProducts: builder.query<Product[], void>({ 
          query: () => "/products",
        }),  // ✅ No arguments required
      getProductById: builder.query<Product, string>({
        query: (id) => `/products/${id}`,
      }),
    }),
  });

export const { useGetProductsQuery, useGetProductByIdQuery } = productApi; // Export the hook generated by RTK Query