import { Product } from "../models/Product";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const API_URL = "https://fakestoreapi.com";

export const productApi = createApi({
    reducerPath: 'productApi', // A unique name for the API slice
    baseQuery: fetchBaseQuery({ baseUrl: API_URL }), // The base URL for the API
    endpoints: (builder) => ({
      getProducts: builder.query<Product[], void>({ // Define a "getProducts" query
        query: () => '/products', // The API endpoint to fetch the products
      }),
    }),
  });

export const { useGetProductsQuery } = productApi; // Export the hook generated by RTK Query